### ISSUE TITLE
Update to latest Bitcore

### ISSUE THREAD

**Issue by slush0** [UdjinM6/insight-api-dash#7]
Hey,

Bitpay recently released new version of Bitcore, which does not compile bitcoind into itself, but uses zero-mq bus for communicating with patched bitcoind. It makes life easier as they removed many hacks from the code and they also reworked the API.

We would like to offer TREZOR+myTREZOR with native DASH support, but for that we need working Bitcore fork for DASH built on this newest API.

**Comment by UdjinM6** [comment]
This repo is no longer supported, it's meant for my own local deving only now. Please follow https://github.com/dashpay/insight-api-dash instead, it should have up to date version afaik (otherwise please submit an issue there). Thanks!
